//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Build Version:.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following toolbar item has been tapped.
        /// </summary>
        public static string CommonToolbarItemTapped {
            get {
                return ResourceManager.GetString("CommonToolbarItemTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string DataUsage {
            get {
                return ResourceManager.GetString("DataUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av. de las Américas 1254, Country Club.
        /// </summary>
        public static string EpamAddress {
            get {
                return ResourceManager.GetString("EpamAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44610 Guadalajara, Jalisco.
        /// </summary>
        public static string EpamAddressLineTwo {
            get {
                return ResourceManager.GetString("EpamAddressLineTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epam Systems Mexico.
        /// </summary>
        public static string EpamSystems {
            get {
                return ResourceManager.GetString("EpamSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.epam.com.
        /// </summary>
        public static string EpamWebSite {
            get {
                return ResourceManager.GetString("EpamWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Favorites button was tapped.
        /// </summary>
        public static string FavoritesButtonPressed {
            get {
                return ResourceManager.GetString("FavoritesButtonPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Help button was tapped.
        /// </summary>
        public static string HelpButtonPressed {
            get {
                return ResourceManager.GetString("HelpButtonPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this App (Tutorial).
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string MenuSearch {
            get {
                return ResourceManager.GetString("MenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Available.
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more ....
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sync button was tapped.
        /// </summary>
        public static string SyncButtonPressed {
            get {
                return ResourceManager.GetString("SyncButtonPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Pins.
        /// </summary>
        public static string ToolbarItemClearPins {
            get {
                return ResourceManager.GetString("ToolbarItemClearPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease text size.
        /// </summary>
        public static string ToolbarItemDecreaseTextSize {
            get {
                return ResourceManager.GetString("ToolbarItemDecreaseTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact by email.
        /// </summary>
        public static string ToolbarItemEmailContact {
            get {
                return ResourceManager.GetString("ToolbarItemEmailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase text size.
        /// </summary>
        public static string ToolbarItemIncreaseTextSize {
            get {
                return ResourceManager.GetString("ToolbarItemIncreaseTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by date.
        /// </summary>
        public static string ToolbarItemOrderByDate {
            get {
                return ResourceManager.GetString("ToolbarItemOrderByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by popularity.
        /// </summary>
        public static string ToolbarItemOrderByPopularity {
            get {
                return ResourceManager.GetString("ToolbarItemOrderByPopularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact by phone.
        /// </summary>
        public static string ToolbarItemPhoneContact {
            get {
                return ResourceManager.GetString("ToolbarItemPhoneContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Map.
        /// </summary>
        public static string ToolbarItemResetMap {
            get {
                return ResourceManager.GetString("ToolbarItemResetMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Location.
        /// </summary>
        public static string ToolbarItemSearchLocation {
            get {
                return ResourceManager.GetString("ToolbarItemSearchLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show My Location.
        /// </summary>
        public static string ToolbarItemShowMyLocation {
            get {
                return ResourceManager.GetString("ToolbarItemShowMyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact by whats app.
        /// </summary>
        public static string ToolbarItemWhatsAppContact {
            get {
                return ResourceManager.GetString("ToolbarItemWhatsAppContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque hendrerit sem tristique metus suscipit malesuada id et diam. Pellentesque volutpat tortor a orci rutrum, sed pharetra ex eleifend..
        /// </summary>
        public static string WizzardStep1Text {
            get {
                return ResourceManager.GetString("WizzardStep1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Number 1.
        /// </summary>
        public static string WizzardStep1Title {
            get {
                return ResourceManager.GetString("WizzardStep1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nullam posuere nulla ac condimentum volutpat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed a massa nec metus vulputate dignissim a vitae nulla..
        /// </summary>
        public static string WizzardStep2Text {
            get {
                return ResourceManager.GetString("WizzardStep2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Number 2.
        /// </summary>
        public static string WizzardStep2Title {
            get {
                return ResourceManager.GetString("WizzardStep2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duis ut ultrices neque, sed dignissim nulla. Donec est ipsum, elementum a dolor vel, ornare aliquet urna. In elementum massa et sodales imperdiet. Ut at nisl sed purus commodo placerat congue sed quam..
        /// </summary>
        public static string WizzardStep3Text {
            get {
                return ResourceManager.GetString("WizzardStep3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Number 3.
        /// </summary>
        public static string WizzardStep3Title {
            get {
                return ResourceManager.GetString("WizzardStep3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone.
        /// </summary>
        public static string YourPhone {
            get {
                return ResourceManager.GetString("YourPhone", resourceCulture);
            }
        }
    }
}
